#pragma once

// from glfw3.h

#define CRAGINE_MOUSE_BUTTON_1         0
#define CRAGINE_MOUSE_BUTTON_2         1
#define CRAGINE_MOUSE_BUTTON_3         2
#define CRAGINE_MOUSE_BUTTON_4         3
#define CRAGINE_MOUSE_BUTTON_5         4
#define CRAGINE_MOUSE_BUTTON_6         5
#define CRAGINE_MOUSE_BUTTON_7         6
#define CRAGINE_MOUSE_BUTTON_8         7
#define CRAGINE_MOUSE_BUTTON_LAST      CRAGINE_MOUSE_BUTTON_8
#define CRAGINE_MOUSE_BUTTON_LEFT      CRAGINE_MOUSE_BUTTON_1
#define CRAGINE_MOUSE_BUTTON_RIGHT     CRAGINE_MOUSE_BUTTON_2
#define CRAGINE_MOUSE_BUTTON_MIDDLE    CRAGINE_MOUSE_BUTTON_3